// <auto-generated/>
using KiotaSupersetAPI.Client.Api.V1.Database.Item.Table_extra.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using System.Linq;

namespace KiotaSupersetAPI.Client.Api.V1.Database.Item.Table_extra
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v1\database\{pk}\table_extra
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.16.0")]
    public partial class Table_extraRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the KiotaSupersetAPI.Client.api.v1.database.item.table_extra.item collection</summary>
        /// <param name="position">Table name</param>
        /// <returns>A <see cref="global::KiotaSupersetAPI.Client.Api.V1.Database.Item.Table_extra.Item.WithTable_nameItemRequestBuilder"/></returns>
        public global::KiotaSupersetAPI.Client.Api.V1.Database.Item.Table_extra.Item.WithTable_nameItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("table_name", position);
                return new global::KiotaSupersetAPI.Client.Api.V1.Database.Item.Table_extra.Item.WithTable_nameItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::KiotaSupersetAPI.Client.Api.V1.Database.Item.Table_extra.Table_extraRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Table_extraRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/database/{pk}/table_extra", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::KiotaSupersetAPI.Client.Api.V1.Database.Item.Table_extra.Table_extraRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Table_extraRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/database/{pk}/table_extra", rawUrl)
        {
        }
    }
}
