// <auto-generated/>
using System.Runtime.Serialization;
using System;
using System.Linq;

namespace KiotaSupersetAPI.Client.Models.FilterSetRestApi
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.16.0")]
    #pragma warning disable CS1591
    public enum Put_owner_type
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "Dashboard")]
        #pragma warning disable CS1591
        Dashboard,
        #pragma warning restore CS1591
    }
}
