
using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Abstractions.Serialization;
using KClient = KiotaSupersetAPI.Client;

namespace KiotaSupersetAPI.Client.API.Chart.Item.Thumbnail.Item;

/// <summary>
/// Builds and executes requests for operations under \api\v1\chart\{pk}\thumbnail\{digest}
/// </summary>
[GeneratedCode("Kiota", "1.16.0")]
public partial class WithDigestItemRequestBuilder : BaseRequestBuilder
{
    /// <summary>
    /// Instantiates a new <see cref="Chart.Item.Thumbnail.Item.WithDigestItemRequestBuilder"/> and sets the default values.
    /// </summary>
    /// <param name="pathParameters">Path parameters for the request</param>
    /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
    public WithDigestItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/chart/{pk}/thumbnail/{digest}", pathParameters)
    {
    }
    /// <summary>
    /// Instantiates a new <see cref="Chart.Item.Thumbnail.Item.WithDigestItemRequestBuilder"/> and sets the default values.
    /// </summary>
    /// <param name="rawUrl">The raw URL to use for the request builder.</param>
    /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
    public WithDigestItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/chart/{pk}/thumbnail/{digest}", rawUrl)
    {
    }
    /// <summary>
    /// Compute or get already computed chart thumbnail from cache.
    /// </summary>
    /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
    /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
    /// <exception cref="KClient.Models.WithDigest400Error">When receiving a 400 status code</exception>
    /// <exception cref="KClient.Models.WithDigest401Error">When receiving a 401 status code</exception>
    /// <exception cref="KClient.Models.WithDigest404Error">When receiving a 404 status code</exception>
    /// <exception cref="KClient.Models.WithDigest500Error">When receiving a 500 status code</exception>
    public async Task GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
    {

        var requestInfo = ToGetRequestInformation(requestConfiguration);
        var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
        {
            { "400", KClient.Models.WithDigest400Error.CreateFromDiscriminatorValue },
            { "401", KClient.Models.WithDigest401Error.CreateFromDiscriminatorValue },
            { "404", KClient.Models.WithDigest404Error.CreateFromDiscriminatorValue },
            { "500", KClient.Models.WithDigest500Error.CreateFromDiscriminatorValue },
        };
        await RequestAdapter.SendNoContentAsync(requestInfo, errorMapping, cancellationToken).ConfigureAwait(false);
    }
    /// <summary>
    /// Compute or get already computed chart thumbnail from cache.
    /// </summary>
    /// <returns>A <see cref="RequestInformation"/></returns>
    /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
    public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
    {

        var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
        requestInfo.Configure(requestConfiguration);
        requestInfo.Headers.TryAdd("Accept", "image/*, application/json");
        return requestInfo;
    }
    /// <summary>
    /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
    /// </summary>
    /// <returns>A <see cref="Chart.Item.Thumbnail.Item.WithDigestItemRequestBuilder"/></returns>
    /// <param name="rawUrl">The raw URL to use for the request builder.</param>
    public Chart.Item.Thumbnail.Item.WithDigestItemRequestBuilder WithUrl(string rawUrl)
    {
        return new Chart.Item.Thumbnail.Item.WithDigestItemRequestBuilder(rawUrl, RequestAdapter);
    }
    /// <summary>
    /// Configuration for the request such as headers, query parameters, and middleware options.
    /// </summary>
    [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
    [GeneratedCode("Kiota", "1.16.0")]
    public partial class WithDigestItemRequestBuilderGetRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
    {
    }
}
