// <auto-generated/>
using System.Runtime.Serialization;
using System;
using System.CodeDom.Compiler;
using System.Linq;

using Api = KiotaSupersetAPI.Client.Api.V1;

namespace KiotaSupersetAPI.Client.Models
{
    [GeneratedCode("Kiota", "1.16.0")]
    /// <summary>The recipient type, check spec for valid options</summary>
    public enum ReportRecipient_type
    {
        [EnumMember(Value = "Email")]
        #pragma warning disable CS1591
        Email,
        #pragma warning restore CS1591
        [EnumMember(Value = "Slack")]
        #pragma warning disable CS1591
        Slack,
        #pragma warning restore CS1591
    }
}
