// <auto-generated/>
using KiotaSupersetAPI.Client.Api.V1.Advanced_data_type;
using KiotaSupersetAPI.Client.Api.V1.Annotation_layer;
using KiotaSupersetAPI.Client.Api.V1.Assets;
using KiotaSupersetAPI.Client.Api.V1.Async_event;
using KiotaSupersetAPI.Client.Api.V1.Available_domains;
using KiotaSupersetAPI.Client.Api.V1.Cachekey;
using KiotaSupersetAPI.Client.Api.V1.Chart;
using KiotaSupersetAPI.Client.Api.V1.Css_template;
using KiotaSupersetAPI.Client.Api.V1.Dashboard;
using KiotaSupersetAPI.Client.Api.V1.Database;
using KiotaSupersetAPI.Client.Api.V1.Dataset;
using KiotaSupersetAPI.Client.Api.V1.Datasource;
using KiotaSupersetAPI.Client.Api.V1.Embedded_dashboard;
using KiotaSupersetAPI.Client.Api.V1.Explore;
using KiotaSupersetAPI.Client.Api.V1.Log;
using KiotaSupersetAPI.Client.Api.V1.Me;
using KiotaSupersetAPI.Client.Api.V1.Menu;
using KiotaSupersetAPI.Client.Api.V1.Query;
using KiotaSupersetAPI.Client.Api.V1.Report;
using KiotaSupersetAPI.Client.Api.V1.Rowlevelsecurity;
using KiotaSupersetAPI.Client.Api.V1.Saved_query;
using KiotaSupersetAPI.Client.Api.V1.Security;
using KiotaSupersetAPI.Client.Api.V1.Sqllab;
using KiotaSupersetAPI.Client.Api.V1.Tag;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using System.CodeDom.Compiler;
using System.Linq;

using KApi = KiotaSupersetAPI.Client.Api.V1;
using KClient = KiotaSupersetAPI.Client;

namespace KiotaSupersetAPI.Client.Api.V1
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v1
    /// </summary>
    [GeneratedCode("Kiota", "1.16.0")]
    public partial class V1RequestBuilder : BaseRequestBuilder
    {
        /// <summary>The advanced_data_type property</summary>
        public global::KiotaSupersetAPI.Client.Api.V1.Advanced_data_type.Advanced_data_typeRequestBuilder Advanced_data_type
        {
            get => new global::KiotaSupersetAPI.Client.Api.V1.Advanced_data_type.Advanced_data_typeRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The annotation_layer property</summary>
        public global::KiotaSupersetAPI.Client.Api.V1.Annotation_layer.Annotation_layerRequestBuilder Annotation_layer
        {
            get => new global::KiotaSupersetAPI.Client.Api.V1.Annotation_layer.Annotation_layerRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The assets property</summary>
        public global::KiotaSupersetAPI.Client.Api.V1.Assets.AssetsRequestBuilder Assets
        {
            get => new global::KiotaSupersetAPI.Client.Api.V1.Assets.AssetsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The async_event property</summary>
        public global::KiotaSupersetAPI.Client.Api.V1.Async_event.Async_eventRequestBuilder Async_event
        {
            get => new global::KiotaSupersetAPI.Client.Api.V1.Async_event.Async_eventRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The available_domains property</summary>
        public global::KiotaSupersetAPI.Client.Api.V1.Available_domains.Available_domainsRequestBuilder Available_domains
        {
            get => new global::KiotaSupersetAPI.Client.Api.V1.Available_domains.Available_domainsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The cachekey property</summary>
        public global::KiotaSupersetAPI.Client.Api.V1.Cachekey.CachekeyRequestBuilder Cachekey
        {
            get => new global::KiotaSupersetAPI.Client.Api.V1.Cachekey.CachekeyRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The chart property</summary>
        public global::KiotaSupersetAPI.Client.Api.V1.Chart.ChartRequestBuilder Chart
        {
            get => new global::KiotaSupersetAPI.Client.Api.V1.Chart.ChartRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The css_template property</summary>
        public global::KiotaSupersetAPI.Client.Api.V1.Css_template.Css_templateRequestBuilder Css_template
        {
            get => new global::KiotaSupersetAPI.Client.Api.V1.Css_template.Css_templateRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The dashboard property</summary>
        public global::KiotaSupersetAPI.Client.Api.V1.Dashboard.DashboardRequestBuilder Dashboard
        {
            get => new global::KiotaSupersetAPI.Client.Api.V1.Dashboard.DashboardRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The database property</summary>
        public global::KiotaSupersetAPI.Client.Api.V1.Database.DatabaseRequestBuilder Database
        {
            get => new global::KiotaSupersetAPI.Client.Api.V1.Database.DatabaseRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The dataset property</summary>
        public global::KiotaSupersetAPI.Client.Api.V1.Dataset.DatasetRequestBuilder Dataset
        {
            get => new global::KiotaSupersetAPI.Client.Api.V1.Dataset.DatasetRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The datasource property</summary>
        public global::KiotaSupersetAPI.Client.Api.V1.Datasource.DatasourceRequestBuilder Datasource
        {
            get => new global::KiotaSupersetAPI.Client.Api.V1.Datasource.DatasourceRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The embedded_dashboard property</summary>
        public global::KiotaSupersetAPI.Client.Api.V1.Embedded_dashboard.Embedded_dashboardRequestBuilder Embedded_dashboard
        {
            get => new global::KiotaSupersetAPI.Client.Api.V1.Embedded_dashboard.Embedded_dashboardRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The explore property</summary>
        public global::KiotaSupersetAPI.Client.Api.V1.Explore.ExploreRequestBuilder Explore
        {
            get => new global::KiotaSupersetAPI.Client.Api.V1.Explore.ExploreRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The log property</summary>
        public global::KiotaSupersetAPI.Client.Api.V1.Log.LogRequestBuilder Log
        {
            get => new global::KiotaSupersetAPI.Client.Api.V1.Log.LogRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The me property</summary>
        public global::KiotaSupersetAPI.Client.Api.V1.Me.MeRequestBuilder Me
        {
            get => new global::KiotaSupersetAPI.Client.Api.V1.Me.MeRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The menu property</summary>
        public global::KiotaSupersetAPI.Client.Api.V1.Menu.MenuRequestBuilder Menu
        {
            get => new global::KiotaSupersetAPI.Client.Api.V1.Menu.MenuRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The query property</summary>
        public global::KiotaSupersetAPI.Client.Api.V1.Query.QueryRequestBuilder Query
        {
            get => new global::KiotaSupersetAPI.Client.Api.V1.Query.QueryRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The report property</summary>
        public global::KiotaSupersetAPI.Client.Api.V1.Report.ReportRequestBuilder Report
        {
            get => new global::KiotaSupersetAPI.Client.Api.V1.Report.ReportRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The rowlevelsecurity property</summary>
        public global::KiotaSupersetAPI.Client.Api.V1.Rowlevelsecurity.RowlevelsecurityRequestBuilder Rowlevelsecurity
        {
            get => new global::KiotaSupersetAPI.Client.Api.V1.Rowlevelsecurity.RowlevelsecurityRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The saved_query property</summary>
        public global::KiotaSupersetAPI.Client.Api.V1.Saved_query.Saved_queryRequestBuilder Saved_query
        {
            get => new global::KiotaSupersetAPI.Client.Api.V1.Saved_query.Saved_queryRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The security property</summary>
        public global::KiotaSupersetAPI.Client.Api.V1.Security.SecurityRequestBuilder Security
        {
            get => new global::KiotaSupersetAPI.Client.Api.V1.Security.SecurityRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The sqllab property</summary>
        public global::KiotaSupersetAPI.Client.Api.V1.Sqllab.SqllabRequestBuilder Sqllab
        {
            get => new global::KiotaSupersetAPI.Client.Api.V1.Sqllab.SqllabRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The tag property</summary>
        public global::KiotaSupersetAPI.Client.Api.V1.Tag.TagRequestBuilder Tag
        {
            get => new global::KiotaSupersetAPI.Client.Api.V1.Tag.TagRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::KiotaSupersetAPI.Client.Api.V1.V1RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public V1RequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::KiotaSupersetAPI.Client.Api.V1.V1RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public V1RequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1", rawUrl)
        {
        }
    }
}
